name: Docker Build and Publish Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
        
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'latest'
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}  
          
      - if: github.event.inputs.tag == 'latest'
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ubnalluri/githubaction:latest
          
      - if: github.event.inputs.tag != 'latest'
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ubnalluri/githubaction:${{ github.event.inputs.tag }}

