name: Shell Commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello Welcome to the New World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: running shell Commands
        run: |
          df -h
          hostname

